### ISSUE TITLE
Error with streamlit

### ISSUE THREAD

**Issue by dzungpv** [Anil-matcha/Chatbase#3]
This is the log when I run streamlit
```
2023-06-08 16:07:02.411 Uncaught app exception
Traceback (most recent call last):
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 548, in _run_script
    self._session_state.on_script_will_rerun(rerun_data.widget_states)
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 68, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 482, in on_script_will_rerun
    self._call_callbacks()
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 495, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 247, in call_callback
    callback(*args, **kwargs)
  File "/Users/vietdzung/dev/test/Website-to-Chatbot/streamlitui.py", line 30, in ingest_input
    ingest_text = st.session_state["webquery"].ingest(url)
  File "/Users/vietdzung/dev/test/Website-to-Chatbot/webquery.py", line 27, in ingest
    result = trafilatura.extract(trafilatura.fetch_url(url))
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/site-packages/trafilatura/core.py", line 1050, in extract
    signal(SIGALRM, timeout_handler)
  File "/Users/vietdzung/anaconda3/envs/website2gpt/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

**Comment by Anil-matcha** [comment]
It might be possible the mentioned webpage is unscrapable causing the issue

**Comment by dzungpv** [comment]
The site can access with browser.

**Comment by Anil-matcha** [comment]
@dzungpv Scraping from code is different from browser access. Some websites don't allow scraping
